import { useEffect, useState } from "react";
import { PORTRAIT_MAP, ROLE_MAP } from "../constants";
import type { Hero, Role } from "../types";

interface ApiRecord {
  data: {
    hero: { data: { name: string; head: string } };
    hero_id: number;
  };
}

interface ApiResponse {
  data: { records: ApiRecord[] };
}

function makeId(name: string): string {
  return name.toLowerCase().replace(/[\s'.&]+/g, "_").replace(/_+$/, "");
}

export type HeroSource = "local" | "api" | "fallback";

// Generated by `node scripts/download-heroes.mjs` — shipped in public/.
const LOCAL_MANIFEST = "/heroes.json";
// Dev-only proxy (see vite.config.ts) used only if the local manifest is missing.
const HERO_ENDPOINT = "/mlbb-api/heroes?size=150&index=1&order=desc&lang=en";

interface ManifestEntry {
  heroId: number;
  name: string;
  id: string;
  smallmap: string;
  head: string;
}

export function useHeroes() {
  const [heroes, setHeroes] = useState<Hero[]>([]);
  const [loading, setLoading] = useState(true);
  const [source, setSource] = useState<HeroSource>("local");

  useEffect(() => {
    // 1. Try local manifest first — instant, no network, works offline.
    fetch(LOCAL_MANIFEST)
      .then(r => {
        if (!r.ok) throw new Error(`heroes.json HTTP ${r.status}`);
        return r.json() as Promise<ManifestEntry[]>;
      })
      .then(entries => {
        const list: Hero[] = entries
          .map(e => ({
            id: e.id,
            name: e.name,
            heroId: e.heroId,
            role: (ROLE_MAP[e.name] ?? "Fighter") as Role,
            head: e.head,
            image: PORTRAIT_MAP[e.name] ?? null,
            smallmap: e.smallmap,
          }))
          .sort((a, b) => a.name.localeCompare(b.name));
        setHeroes(list);
        setSource("local");
        setLoading(false);
      })
      .catch(localErr => {
        console.warn("[useHeroes] Local manifest missing, hitting live API:", localErr);
        // 2. Live API (dev proxy in dev, raw URL in prod — will CORS-fail in prod).
        fetch(HERO_ENDPOINT)
          .then(r => {
            if (!r.ok) throw new Error(`Hero API HTTP ${r.status}`);
            return r.json() as Promise<ApiResponse>;
          })
          .then(data => {
            const list: Hero[] = data.data.records
              .map(r => ({
                id: makeId(r.data.hero.data.name),
                name: r.data.hero.data.name,
                heroId: r.data.hero_id,
                role: (ROLE_MAP[r.data.hero.data.name] ?? "Fighter") as Role,
                head: r.data.hero.data.head,
                image: PORTRAIT_MAP[r.data.hero.data.name] ?? null,
                smallmap: null,
              }))
              .sort((a, b) => a.name.localeCompare(b.name));
            setHeroes(list);
            setSource("api");
            setLoading(false);
          })
          .catch(apiErr => {
            // 3. Last resort: ROLE_MAP names with no portraits at all.
            console.error("[useHeroes] API fetch failed, using ROLE_MAP fallback:", apiErr);
            const list: Hero[] = Object.entries(ROLE_MAP)
              .map(([name, role]) => ({
                id: makeId(name),
                name,
                role,
                head: null,
                image: PORTRAIT_MAP[name] ?? null,
                smallmap: null,
              }))
              .sort((a, b) => a.name.localeCompare(b.name));
            setHeroes(list);
            setSource("fallback");
            setLoading(false);
          });
      });
  }, []);

  return { heroes, loading, source, setHeroes };
}
